# Generated by Django 5.2.8 on 2025-11-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=150)),
                ('courriel', models.EmailField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('Prospect', 'Prospect'), ('Fidele', 'Fidèle')], default='Prospect', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activite', models.DateField(auto_now_add=True)),
                ('type_activite', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='clients.client')),
            ],
        ),
    ]
