# Generated by Django 5.2.8 on 2025-11-22 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, unique=True)),
                ('montant_ht', models.FloatField()),
                ('tps', models.FloatField()),
                ('tvq', models.FloatField()),
                ('montant_ttc', models.FloatField()),
                ('montant_paye', models.FloatField(default=0)),
                ('statut_paiement', models.CharField(choices=[('En attente', 'En attente'), ('Partielle', 'Partielle'), ('Payée', 'Payée')], default='En attente', max_length=20)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametreFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tps', models.FloatField(default=0.05)),
                ('tvq', models.FloatField(default=0.09975)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('Carte', 'Carte'), ('Virement', 'Virement'), ('Comptant', 'Comptant')], default='Carte', max_length=20)),
                ('montant', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='ventes.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('statut_commande', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Facturée', 'Facturée'), ('Payée', 'Payée'), ('Annulée', 'Annulée')], default='Brouillon', max_length=20)),
                ('sous_total', models.FloatField(default=0)),
                ('tps', models.FloatField(default=0)),
                ('tvq', models.FloatField(default=0)),
                ('montant_total', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.FloatField()),
                ('cout_achat_unitaire', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='vente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='ventes.vente'),
        ),
    ]
