# Generated by Django 5.2.8 on 2025-11-22 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=100)),
                ('code_fournisseur', models.CharField(max_length=50)),
                ('remise_fournisseur', models.FloatField(default=0.0)),
                ('delai_livraison', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nom_produit', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prix_unitaire', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cout_achat', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantite_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('seuil_reappro', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=20)),
                ('delai_livraison', models.IntegerField(default=5)),
                ('poids_kg', models.FloatField(default=0)),
                ('emplacement', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.category')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=3)),
                ('quantite', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
